<script src="js/newQuery.js"></script>

<a class="return" href="/">Назад</a>

<h2>Инструмент анализа ТОП по ключевым показателям</h2>

<form action="">
    <div class="row">
        <input type="text" name="query" placeholder="Ключевое слово: *" value="" required>
    </div>
    <div class="row">
        <div class="field-name">Продвигаемые URL</div>
        <input type="file" name="url" id="url">
    </div>
    <div class="row">
        <label><input type="checkbox" name="rel_url" >Определить релевантный URL по выдаче</label>
    </div>
    <div class="row">
        <label><input type="checkbox" name="manual_urls" >Ручной выбор URL для анализа</label>
    </div>
    <div class="row urls" style="display:none">
        <div class="field-name">Список URL для анализа от 1 до 20 штук</div>
        <textarea name="user_urls" placeholder="Каждый URL с новой строки"></textarea>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="field-name">Поисковая система</div>
            <select name="search_system" id="ss" data-placeholder="Поисковая система: *">
                <option value="1"
                        selected                                                                         >Яндекс</option>
                <option value="2"
                >Google.ru</option>
                <option value="3"
                >Google.com.ua</option>
                <option value="4"
                >Google.kz</option>
                <option value="5"
                >Google.by</option>
            </select>
        </div>
        <div class="col-lg-6">
            <div class="field-name">Регион</div>
            <select name="lr" id="region" data-placeholder="Регион: *">
                <option value="213" selected >Москва</option>
                <option value="2">Санкт-Петербург</option>
                <option value="54">Екатеринбург</option>
                <option value="43">Казань</option>
                <option value="47">Нижний Новгород</option>
                <option value="65">Новосибирск</option>
                <option value="66">Омск</option>
                <option value="39">Ростов-на-Дону</option>
                <option value="51">Самара</option>
                <option value="172">Уфа</option>
                <option value="56">Челябинск</option>
                <option value="38">Волгоград</option>
                <option value="193">Воронеж</option>
                <option value="62">Красноярск</option>
                <option value="50">Пермь</option>
                <option value="216">Зеленоград</option>
                <option value="10735">Красногорск</option>
                <option value="10743">Одинцово</option>
                <option value="10758">Химки</option>
                <option value="1095">Абакан</option>
                <option value="29386">Абхазия</option>
                <option value="29403">Акмолинская область</option>
                <option value="20273">Актобе</option>
                <option value="29404">Актюбинская область</option>
                <option value="10656">Александров</option>
                <option value="29406">Алматинская область</option>
                <option value="162">Алматы</option>
                <option value="11235">Алтайский край</option>
                <option value="11471">Алушта</option>
                <option value="11121">Альметьевск</option>
                <option value="11375">Амурская область</option>
                <option value="11458">Анадырь</option>
                <option value="1107">Анапа</option>
                <option value="11256">Ангарск</option>
                <option value="10894">Апатиты</option>
                <option value="11080">Арзамас</option>
                <option value="10987">Армавир</option>
                <option value="168">Армения</option>
                <option value="20">Архангельск</option>
                <option value="10842">Архангельская область</option>
                <option value="163">Астана</option>
                <option value="10946">Астраханская область</option>
                <option value="37">Астрахань</option>
                <option value="29407">Атырауская область</option>
                <option value="11302">Ачинск</option>
                <option value="11143">Балаково</option>
                <option value="10716">Балашиха</option>
                <option value="197">Барнаул</option>
                <option value="149">Беларусь</option>
                <option value="10369">Белая Церковь</option>
                <option value="4">Белгород</option>
                <option value="10645">Белгородская область</option>
                <option value="11374">Белогорск</option>
                <option value="10314">Бельцы</option>
                <option value="10315">Бендеры</option>
                <option value="11314">Бердск</option>
                <option value="975">Бийск</option>
                <option value="11393">Биробиджан</option>
                <option value="77">Благовещенск</option>
                <option value="976">Братск</option>
                <option value="153">Брест</option>
                <option value="29632">Брестская область</option>
                <option value="191">Брянск</option>
                <option value="10650">Брянская область</option>
                <option value="11122">Бугульма</option>
                <option value="87">Вашингтон</option>
                <option value="10928">Великие Луки</option>
                <option value="24">Великий Новгород</option>
                <option value="10719">Видное</option>
                <option value="963">Винница</option>
                <option value="20545">Винницкая область</option>
                <option value="154">Витебск</option>
                <option value="29633">Витебская область</option>
                <option value="75">Владивосток</option>
                <option value="33">Владикавказ</option>
                <option value="192">Владимир</option>
                <option value="10658">Владимирcкая область</option>
                <option value="10950">Волгоградская область</option>
                <option value="11036">Волгодонск</option>
                <option value="10951">Волжский</option>
                <option value="21">Вологда</option>
                <option value="10853">Вологодская область</option>
                <option value="20550">Волынская область</option>
                <option value="10672">Воронежcкая область</option>
                <option value="29408">Восточно-Казахстанская область</option>
                <option value="10867">Гатчина</option>
                <option value="97">Гейдельберг</option>
                <option value="10990">Геленджик</option>
                <option value="11150">Глазов</option>
                <option value="155">Гомель</option>
                <option value="29631">Гомельская область</option>
                <option value="11319">Горно-Алтайск</option>
                <option value="29634">Гродненская область</option>
                <option value="10274">Гродно</option>
                <option value="1106">Грозный</option>
                <option value="169">Грузия</option>
                <option value="10661">Гусь-Хрустальный</option>
                <option value="21772">Даллас</option>
                <option value="89">Детройт</option>
                <option value="972">Дзержинск</option>
                <option value="11155">Димитровград</option>
                <option value="10723">Дмитров</option>
                <option value="141">Днепр</option>
                <option value="20537">Днепропетровская область</option>
                <option value="214">Долгопрудный</option>
                <option value="10725">Домодедово</option>
                <option value="142">Донецк</option>
                <option value="20536">Донецкая область</option>
                <option value="102445">Другие города региона</option>
                <option value="215">Дубна</option>
                <option value="11463">Евпатория</option>
                <option value="10243">Еврейская автономная область</option>
                <option value="10993">Ейск</option>
                <option value="11123">Елабуга</option>
                <option value="11057">Ессентуки</option>
                <option value="29409">Жамбылская область</option>
                <option value="20086">Железногорск</option>
                <option value="21622">Железнодорожный</option>
                <option value="11132">Жигулевск</option>
                <option value="10343">Житомир</option>
                <option value="20547">Житомирская область</option>
                <option value="26034">Жодино</option>
                <option value="20571">Жуковский</option>
                <option value="21949">Забайкальский край</option>
                <option value="20530">Закарпатская область</option>
                <option value="29410">Западно-Казахстанская область</option>
                <option value="20539">Запорожская область</option>
                <option value="960">Запорожье</option>
                <option value="11125">Зеленодольск</option>
                <option value="11202">Златоуст</option>
                <option value="10345">Ивано-Франковск</option>
                <option value="20532">Ивано-Франковская область</option>
                <option value="5">Иваново</option>
                <option value="10687">Ивановская область</option>
                <option value="44">Ижевск</option>
                <option value="63">Иркутск</option>
                <option value="11266">Иркутская область</option>
                <option value="11173">Ишим</option>
                <option value="41">Йошкар-Ола</option>
                <option value="159">Казахстан</option>
                <option value="11306">Кайеркан</option>
                <option value="22">Калининград</option>
                <option value="10857">Калининградская область</option>
                <option value="6">Калуга</option>
                <option value="10693">Калужская область</option>
                <option value="11164">Каменск-Уральский</option>
                <option value="11043">Каменск-Шахтинский</option>
                <option value="11398">Камчатский край</option>
                <option value="164">Караганда</option>
                <option value="29411">Карагандинская область</option>
                <option value="11020">Карачаево-Черкесская Республика</option>
                <option value="64">Кемерово</option>
                <option value="11282">Кемеровская область</option>
                <option value="11464">Керчь</option>
                <option value="143">Киев</option>
                <option value="20544">Киевская область</option>
                <option value="20574">Кипр</option>
                <option value="207">Киргизия</option>
                <option value="46">Киров</option>
                <option value="11071">Кирово-Чепецк</option>
                <option value="20221">Кировоград</option>
                <option value="20548">Кировоградская область</option>
                <option value="11070">Кировская область</option>
                <option value="11062">Кисловодск</option>
                <option value="10313">Кишинев</option>
                <option value="10733">Клин</option>
                <option value="10664">Ковров</option>
                <option value="20809">Кокшетау</option>
                <option value="10734">Коломна</option>
                <option value="33883">Комрат</option>
                <option value="11453">Комсомольск-на-Амуре</option>
                <option value="20728">Королёв</option>
                <option value="29412">Костанайская область</option>
                <option value="7">Кострома</option>
                <option value="10699">Костромская область</option>
                <option value="20554">Краматорск</option>
                <option value="35">Краснодар</option>
                <option value="10995">Краснодарский край</option>
                <option value="11309">Красноярский край</option>
                <option value="21609">Кременчуг</option>
                <option value="10347">Кривой Рог</option>
                <option value="977">Крым</option>
                <option value="115092">Крымский федеральный округ</option>
                <option value="20044">Кстово</option>
                <option value="53">Курган</option>
                <option value="11158">Курганская область</option>
                <option value="8">Курск</option>
                <option value="10705">Курская область</option>
                <option value="11333">Кызыл</option>
                <option value="29413">Кызылординская область</option>
                <option value="206">Латвия</option>
                <option value="9">Липецк</option>
                <option value="10712">Липецкая область</option>
                <option value="200">Лос-Анджелес</option>
                <option value="222">Луганск</option>
                <option value="20540">Луганская область</option>
                <option value="20222">Луцк</option>
                <option value="144">Львов</option>
                <option value="20529">Львовская область</option>
                <option value="10738">Люберцы</option>
                <option value="79">Магадан</option>
                <option value="11403">Магаданская область</option>
                <option value="235">Магнитогорск</option>
                <option value="1093">Майкоп</option>
                <option value="24876">Макеевка</option>
                <option value="10069">Мальта</option>
                <option value="29414">Мангистауская область</option>
                <option value="10366">Мариуполь</option>
                <option value="28">Махачкала</option>
                <option value="11287">Междуреченск</option>
                <option value="20271">Мексика</option>
                <option value="10367">Мелитополь</option>
                <option value="11212">Миасс</option>
                <option value="11063">Минеральные Воды</option>
                <option value="157">Минск</option>
                <option value="29630">Минская область</option>
                <option value="158">Могилев</option>
                <option value="29629">Могилевская область</option>
                <option value="208">Молдова</option>
                <option value="1">Москва и область</option>
                <option value="23">Мурманск</option>
                <option value="10897">Мурманская область</option>
                <option value="10668">Муром</option>
                <option value="10740">Мытищи</option>
                <option value="236">Набережные Челны</option>
                <option value="1092">Назрань</option>
                <option value="30">Нальчик</option>
                <option value="974">Находка</option>
                <option value="11064">Невинномысск</option>
                <option value="10176">Ненецкий АО</option>
                <option value="11114">Нефтекамск</option>
                <option value="118">Нидерланды</option>
                <option value="11079">Нижегородская область</option>
                <option value="1091">Нижневартовск</option>
                <option value="11127">Нижнекамск</option>
                <option value="11168">Нижний Тагил</option>
                <option value="148">Николаев</option>
                <option value="20543">Николаевская область</option>
                <option value="10904">Новгородская область</option>
                <option value="237">Новокузнецк</option>
                <option value="10830">Новомосковск</option>
                <option value="970">Новороссийск</option>
                <option value="11316">Новосибирская область</option>
                <option value="11170">Новоуральск</option>
                <option value="238">Новочеркасск</option>
                <option value="10742">Ногинск</option>
                <option value="11311">Норильск</option>
                <option value="967">Обнинск</option>
                <option value="382">Общероссийские</option>
                <option value="145">Одесса</option>
                <option value="20541">Одесская область</option>
                <option value="11214">Озерск</option>
                <option value="11318">Омская область</option>
                <option value="10">Орел</option>
                <option value="48">Оренбург</option>
                <option value="11084">Оренбургская область</option>
                <option value="10745">Орехово-Зуево</option>
                <option value="10772">Орловская область</option>
                <option value="11091">Орск</option>
                <option value="10746">Павловский Посад</option>
                <option value="190">Павлодар</option>
                <option value="29415">Павлодарская область</option>
                <option value="49">Пенза</option>
                <option value="11095">Пензенская область</option>
                <option value="11171">Первоуральск</option>
                <option value="10837">Переславль</option>
                <option value="11108">Пермский край</option>
                <option value="18">Петрозаводск</option>
                <option value="78">Петропавловск-Камчатский</option>
                <option value="40">Поволжье</option>
                <option value="10747">Подольск</option>
                <option value="964">Полтава</option>
                <option value="20549">Полтавская область</option>
                <option value="11409">Приморский край</option>
                <option value="11291">Прокопьевск</option>
                <option value="102473">Прочее</option>
                <option value="25">Псков</option>
                <option value="10926">Псковская область</option>
                <option value="10748">Пушкино</option>
                <option value="217">Пущино</option>
                <option value="11067">Пятигорск</option>
                <option value="10750">Раменское</option>
                <option value="11004">Республика Адыгея</option>
                <option value="10231">Республика Алтай</option>
                <option value="11111">Республика Башкортостан</option>
                <option value="11330">Республика Бурятия</option>
                <option value="11010">Республика Дагестан</option>
                <option value="11012">Республика Ингушетия</option>
                <option value="11013">Республика Кабардино-Балкария</option>
                <option value="11015">Республика Калмыкия</option>
                <option value="10933">Республика Карелия</option>
                <option value="10939">Республика Коми</option>
                <option value="11077">Республика Марий Эл</option>
                <option value="11117">Республика Мордовия</option>
                <option value="11443">Республика Саха (Якутия)</option>
                <option value="11021">Республика Северная Осетия-Алания</option>
                <option value="10233">Республика Тыва</option>
                <option value="11340">Республика Хакасия</option>
                <option value="21621">Реутов</option>
                <option value="10820">Ржев</option>
                <option value="20534">Ровенская область</option>
                <option value="10355">Ровно</option>
                <option value="225">Россия</option>
                <option value="10838">Ростов</option>
                <option value="11029">Ростовская область</option>
                <option value="11251">Рубцовск</option>
                <option value="10839">Рыбинск</option>
                <option value="10776">Рязанская область</option>
                <option value="11">Рязань</option>
                <option value="11115">Салават</option>
                <option value="58">Салехард</option>
                <option value="11131">Самарская область</option>
                <option value="21749">Сан-Антонио</option>
                <option value="21754">Сан-Диего</option>
                <option value="90">Сан-Франциско</option>
                <option value="21756">Сан-Хосе</option>
                <option value="10174">Санкт-Петербург и Ленинградская область</option>
                <option value="42">Саранск</option>
                <option value="11152">Сарапул</option>
                <option value="194">Саратов</option>
                <option value="11146">Саратовская область</option>
                <option value="11083">Саров</option>
                <option value="20258">Сатис</option>
                <option value="11217">Сатка</option>
                <option value="11450">Сахалинская область</option>
                <option value="11341">Саяногорск</option>
                <option value="11162">Свердловская область</option>
                <option value="959">Севастополь</option>
                <option value="102444">Северный Кавказ</option>
                <option value="17">Северо-Запад</option>
                <option value="29416">Северо-Казахстанская область</option>
                <option value="10849">Северодвинск</option>
                <option value="11351">Северск</option>
                <option value="165">Семей</option>
                <option value="180">Сербия</option>
                <option value="10752">Сергиев Посад</option>
                <option value="10754">Серпухов</option>
                <option value="59">Сибирь</option>
                <option value="146">Симферополь</option>
                <option value="121">Словакия</option>
                <option value="122">Словения</option>
                <option value="12">Смоленск</option>
                <option value="10795">Смоленская область</option>
                <option value="166">СНГ</option>
                <option value="11218">Снежинск</option>
                <option value="11110">Соликамск</option>
                <option value="10755">Солнечногорск</option>
                <option value="10937">Сортавала</option>
                <option value="239">Сочи</option>
                <option value="36">Ставрополь</option>
                <option value="11069">Ставропольский край</option>
                <option value="10649">Старый Оскол</option>
                <option value="11116">Стерлитамак</option>
                <option value="980">Страны Балтии</option>
                <option value="10756">Ступино</option>
                <option value="10671">Суздаль</option>
                <option value="20552">Сумская область</option>
                <option value="965">Сумы</option>
                <option value="973">Сургут</option>
                <option value="11139">Сызрань</option>
                <option value="19">Сыктывкар</option>
                <option value="971">Таганрог</option>
                <option value="209">Таджикистан</option>
                <option value="995">Таиланд</option>
                <option value="10303">Талдыкорган</option>
                <option value="13">Тамбов</option>
                <option value="10802">Тамбовская область</option>
                <option value="11119">Татарстан</option>
                <option value="10819">Тверская область</option>
                <option value="14">Тверь</option>
                <option value="10357">Тернополь</option>
                <option value="20531">Тернопольская область</option>
                <option value="10317">Тирасполь</option>
                <option value="11175">Тобольск</option>
                <option value="240">Тольятти</option>
                <option value="67">Томск</option>
                <option value="11353">Томская область</option>
                <option value="20674">Троицк</option>
                <option value="1058">Туапсе</option>
                <option value="15">Тула</option>
                <option value="10832">Тульская область</option>
                <option value="170">Туркмения</option>
                <option value="983">Турция</option>
                <option value="11391">Тында</option>
                <option value="11176">Тюменская область</option>
                <option value="55">Тюмень</option>
                <option value="10840">Углич</option>
                <option value="11148">Удмуртская республика</option>
                <option value="10358">Ужгород</option>
                <option value="171">Узбекистан</option>
                <option value="187">Украина</option>
                <option value="198">Улан-Удэ</option>
                <option value="195">Ульяновск</option>
                <option value="11153">Ульяновская область</option>
                <option value="52">Урал</option>
                <option value="11426">Уссурийск</option>
                <option value="11273">Усть-Илимск</option>
                <option value="10306">Усть-Каменогорск</option>
                <option value="10945">Ухта</option>
                <option value="11469">Феодосия</option>
                <option value="10129">Филадельфия</option>
                <option value="20959">Финикс</option>
                <option value="76">Хабаровск</option>
                <option value="11457">Хабаровский край</option>
                <option value="132">Хайфа</option>
                <option value="57">Ханты-Мансийск</option>
                <option value="11193">Ханты-Мансийский АО</option>
                <option value="147">Харьков</option>
                <option value="20538">Харьковская область</option>
                <option value="962">Херсон</option>
                <option value="20542">Херсонская область</option>
                <option value="20535">Хмельницкая область</option>
                <option value="961">Хмельницкий</option>
                <option value="10130">Хьюстон</option>
                <option value="45">Чебоксары</option>
                <option value="11225">Челябинская область</option>
                <option value="968">Череповец</option>
                <option value="20546">Черкасская область</option>
                <option value="10363">Черкассы</option>
                <option value="1104">Черкесск</option>
                <option value="966">Чернигов</option>
                <option value="20551">Черниговская область</option>
                <option value="20533">Черновицкая область</option>
                <option value="10365">Черновцы</option>
                <option value="219">Черноголовка</option>
                <option value="10761">Чехов</option>
                <option value="11024">Чеченская Республика</option>
                <option value="10131">Чикаго</option>
                <option value="221">Чимкент</option>
                <option value="11129">Чистополь</option>
                <option value="68">Чита</option>
                <option value="11156">Чувашская республика</option>
                <option value="10251">Чукотский автономный округ</option>
                <option value="11053">Шахты</option>
                <option value="101">Штутгарт</option>
                <option value="10765">Щелково</option>
                <option value="20523">Электросталь</option>
                <option value="1094">Элиста</option>
                <option value="11147">Энгельс</option>
                <option value="29387">Южная Осетия</option>
                <option value="29417">Южно-Казахстанская область</option>
                <option value="80">Южно-Сахалинск</option>
                <option value="74">Якутск</option>
                <option value="11470">Ялта</option>
                <option value="11232">Ямало-Ненецкий АО</option>
                <option value="16">Ярославль</option>
                <option value="10841">Ярославская область</option>
                <option value="211">Австралия</option>
                <option value="138">Австралия и Океания</option>
                <option value="113">Австрия</option>
                <option value="167">Азербайджан</option>
                <option value="183">Азия</option>
                <option value="93">Аргентина</option>
                <option value="245">Арктика и Антарктика</option>
                <option value="86">Атланта</option>
                <option value="241">Африка</option>
                <option value="129">Беер-Шева</option>
                <option value="114">Бельгия</option>
                <option value="177">Берлин</option>
                <option value="1004">Ближний Восток</option>
                <option value="115">Болгария</option>
                <option value="223">Бостон</option>
                <option value="94">Бразилия</option>
                <option value="102">Великобритания</option>
                <option value="116">Венгрия</option>
                <option value="969">Выборг</option>
                <option value="20040">Выкса</option>
                <option value="178">Гамбург</option>
                <option value="96">Германия</option>
                <option value="246">Греция</option>
                <option value="73">Дальний Восток</option>
                <option value="203">Дания</option>
                <option value="111">Европа</option>
                <option value="1056">Египет</option>
                <option value="130">Иерусалим</option>
                <option value="181">Израиль</option>
                <option value="994">Индия</option>
                <option value="204">Испания</option>
                <option value="205">Италия</option>
                <option value="95">Канада</option>
                <option value="98">Кельн</option>
                <option value="134">Китай</option>
                <option value="135">Корея</option>
                <option value="117">Литва</option>
                <option value="99">Мюнхен</option>
                <option value="139">Новая Зеландия</option>
                <option value="119">Норвегия</option>
                <option value="202">Нью-Йорк</option>
                <option value="210">Объединенные Арабские Эмираты</option>
                <option value="120">Польша</option>
                <option value="0">Регионы</option>
                <option value="10002">Северная Америка</option>
                <option value="91">Сиэтл</option>
                <option value="84">США</option>
                <option value="131">Тель-Авив</option>
                <option value="102446">Универсальное</option>
                <option value="123">Финляндия</option>
                <option value="100">Франкфурт-на-Майне</option>
                <option value="124">Франция</option>
                <option value="10083">Хорватия</option>
                <option value="3">Центр</option>
                <option value="21610">Черногория</option>
                <option value="125">Чехия</option>
                <option value="126">Швейцария</option>
                <option value="127">Швеция</option>
                <option value="179">Эстония</option>
                <option value="26">Юг</option>
                <option value="10003">Южная Америка</option>
                <option value="137">Япония</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="field-name">Глубина анализа</div>
        <select name="deep" data-placeholder="Глубина анализа: *">
            <option value="5"
                    selected                                                 >ТОП-5</option>
            <option value="10"
            >ТОП-10</option>
            <option value="15"
            >ТОП-15</option>
        </select>
    </div>
    <div class="row">
        <input type="submit" class="btn refresh" value="Проверить">
    </div>
</form>